pipeline:
  nightly:
    image: maxvasin/resolve-docker
    commands:
      - /scripts/package_json patch_dependencies resolve-* $NIGHTLY_VERSION
      - npm install

  tests:
    image: node:9
    commands:
      - cat ./package.json
