pipeline:
  nightly_patch:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - touch .params
      - if [ -z $NIGHTLY_VERSION ]; then exit 0; fi
      - echo NIGHTLY_BUILD_REPO=$DRONE_REPO >> .params
      - /scripts/package_json patch-dependencies @badgeteam/drone-fake $NIGHTLY_VERSION
      - cat .params

  install_packages:
    image: node:9
    commands:
      - npm install


  test:
    image: node:9
    commands:
      - cat ./node_modules/@badgeteam/drone-fake/package.json

  notify_publisher:
    image: plugins/downstream
    server: http://ci.resolve.sh
    fork: true
    wait: true
    repositories:
      - max-vasin/resolve-publisher

    secrets: [ downstream_token ]
    params:
      - ./.params
      - NIGHTLY_BUILD_STATUS=${DRONE_BUILD_STATUS}

    params-from-env:
      - NIGHTLY_VERSION
      - NIGHTLY_PACKAGE






