pipeline:
  nightly_patch:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - if [ -z $NIGHTLY_VERSION ]; then exit 0; fi
      - echo NIGHTLY_REPO=$DRONE_REPO_NAME >> .params
      - echo NIGHTLY_VERSION=$NIGHTLY_VERSION >> .params
      - echo NIGHTLY_CHECK=$(/scripts/package_json name) >> .params
      - /scripts/package_json patch-dependencies @badgeteam/drone-fake $NIGHTLY_VERSION
      - cat .params

  install_packages:
    image: node:9
    commands:
      - npm install


  test:
    image: node:9
    commands:
      - cat ./node_modules/@badgeteam/drone-fake/package.json

  notify_publisher:
    image: plugins/downstream
    server: http://ci.resolve.sh
    fork: true
    wait: true
    repositories:
      - max-vasin/drone-playground-sub1@master

    secrets: [ downstream_token ]
    params:
      - .params




