pipeline:
  nightly:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - if [ -z $NIGHTLY_VERSION]; then exit 0; fi
      - /scripts/package_json patch-dependencies @badgeteam/drone-fake $NIGHTLY_VERSION
      - npm install

  tests:
    image: node:9
    commands:
      - cat ./node_modules/@badgeteam/drone-fake/package.json
