pipeline:
  nightly_patch:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - touch .params
      - if [ -z $NIGHTLY_VERSION ]; then exit 0; fi
      - echo NIGHTLY_BUILD_REPO=$DRONE_REPO >> .nightly
      - /scripts/package_json patch-dependencies @badgeteam/drone-fake $NIGHTLY_VERSION
      - cat .params

  install_packages:
    image: node:9
    commands:
      - npm install


  test:
    image: node:9
    commands:
      - cat ./node_modules/@badgeteam/drone-fake/package.json
      - exit 1

  build_success:
    image: node:9
    commands:
      - echo NIGHTLY_BUILD_STATUS=success >> .nightly
    when:
      status: [ success ]

  build_failure:
    image: node:9
    commands:
      - echo NIGHTLY_BUILD_STATUS=failure >> .nightly
    when:
      status: [ failure ]

  notify_publisher:
    image: plugins/downstream
    server: http://ci.resolve.sh
    fork: true
    wait: true
    repositories:
      - max-vasin/resolve-publisher

    secrets: [ downstream_token ]
    params:
      - .nightly

    params-from-env:
      - NIGHTLY_VERSION
      - NIGHTLY_PACKAGE

    when:
      status: [ success, failure ]






