pipeline:
  nightly_patch:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - if [ -z $NIGHTLY_VERSION]; then exit 0; fi
      - /scripts/package_json patch-dependencies @badgeteam/drone-fake $NIGHTLY_VERSION

  install_packages:
    image: node:9
    commands:
      - npm install


  test:
    image: node:9
    commands:
      - cat ./node_modules/@badgeteam/drone-fake/package.json

  nightly_notify:
    image: node:9
    commands:
      - if [ -z $NIGHTLY_VERSION]; then exit 0; fi
      - echo Notifying publisher...




