pipeline:
  nightly:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - /scripts/package_json patch_dependencies @badgeteam/drone-fake $NIGHTLY_VERSION
      - npm install

  tests:
    image: node:9
    commands:
      - cat ./package.json
