pipeline:
  nightly:
    image: maxvasin/resolve-docker
    pull: true
    commands:
      - if [ -z $NIGHTLY_VERSION]; then exit 1; fi
      - /scripts/package_json patch_dependencies @badgeteam/drone-fake $NIGHTLY_VERSION
      - npm install

  tests:
    image: node:9
    commands:
      - cat ./package.json
